//=========================================================
// src/I2C-EFM8BB31F16G-C-QFN32_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB3_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
#include "i2c.h"
// $[Generated Includes]
// [Generated Includes]$

SI_SBIT (LED1, SFR_P1, 0);             // LED green


//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup(void) {
	// $[SiLabs Startup]
	// [SiLabs Startup]$
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main(void) {

	volatile uint8_t dat;               // Test counter
	volatile uint8_t i;

	// Call hardware initialization routine
	enter_DefaultMode_from_RESET();

//   // If slave is holding SDA low because of an improper SMBus reset or error
//	uint8_t i;                          // Dummy variable counters
//	while(!SDA)
//	{
//		// Provide clock pulses to allow the slave to advance out
//		// of its current state. This will allow it to release SDA.
//		XBR2 = XBR2_XBARE__ENABLED;      // Enable Crossbar
//		SCL = 0;                         // Drive the clock low
//		for(i = 0; i < 255; i++);        // Hold the clock low
//		SCL = 1;                         // Release the clock
//		while(!SCL);                     // Wait for open-drain
//									   // clock output to rise
//		for(i = 0; i < 10; i++);         // Hold the clock high
//		XBR2 = XBR2_XBARE__DISABLED;     // Disable Crossbar
//	}


//   LED1 = LED_OFF;
//   T0_Wait_ms (100);
//   LED1 = LED_ON;
//   T0_Wait_ms (100);
//   LED1 = LED_OFF;
//   T0_Wait_ms (100);
//   LED1 = LED_ON;


   // TEST CODE----------------------------------------------------------------

	dat = 0;                            // Output data counter
	NUM_ERRORS = 0;                     // Error counter
	while (1)
	{
		TARGET = BQ25895_ADDR;             // Target the Slave for next SMBus transfer

		// SMBus Write Sequence
		//	   SMB_Write(0x01);                     // Initiate SMBus write
		//	   SMB_Write(0x04);                     // Initiate SMBus write
//		for(i=0; i<P9242_NUM_COMMANDS; i++) {
		for(i=0; i<0x14+1; i++) {

//		    SMB_DATA_PTR = P9242_REG_DEV_ID_L;
//			SMB_DATA_PTR = P9221_COMMANDS[i];
//			SMB_DATA_PTR = P9242_COMMANDS[i];

			// Write the index of the for-loop (i.e. sweep all regs between 0 and 14)
			*SMB_DATA_ARRAY = i;

			SMB_Write(1);  // Initiate 1-byte SMBus write
//			SMB_Write(2);  // Initiate 2-byte SMBus write

			// SMBus Read Sequence
			SMB_Read();

			// Run to here to view the SMB_DATA_IN and SMB_DATA_OUT variables

			//	   dat++;
			LED1 = !LED1;
			T0_Wait_ms (1);                  // Wait 50 ms until the next cycle
							// so that YELLOW_LED blinks slow
							// enough to see

		}
	}
}
